apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: myapp
spec:
  type: ClusterIP
  selector:
    app: myapp
    color: blue
  ports:
    - name: http
      port: 80
      targetPort: 3000




